version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=hf.co/bartowski/Llama-3.2-1B-Instruct-GGUF
    restart: unless-stopped
    command: >
      bash -c "
        ollama pull hf.co/bartowski/Llama-3.2-1B-Instruct-GGUF &&
        ollama serve
      "

  crypto-news-pipe:
    build: .
    container_name: crypto-news-pipe
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
